fullnameOverride: project-2

global:
  replicaCount: 2

image:
  repository: neoanderson10/project-2
  tag: latest
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: project2.quvonchbekdev.uz
      paths:
        - path: /
          pathType: Prefix
          service:
            name: project-2
            port: 80
  tls:
    - hosts:
        - project2.quvonchbekdev.uz
      secretName: project2-quvonchbekdev-uz-tls
