apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project-1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/abbos1117/helm-chart.git'
    targetRevision: main
    path: mychart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: project-1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
