fullnameOverride: project-1

global:
  replicaCount: 1

image:
  repository: neoanderson10/project-1
  tag: latest
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: project1.quvonchbekdev.uz
      paths:
        - path: /
          pathType: Prefix
          service:
            name: project-1
            port: 80
  tls:
    - hosts:
        - project1.quvonchbekdev.uz
      secretName: project1-quvonchbekdev-uz-tls
